
FROM node:18-alpine AS builder
WORKDIR /app
COPY tp-frontend-basique/frontend-react-api/package*.json ./frontend/
RUN cd frontend && npm ci
COPY tp-frontend-basique/frontend-react-api ./frontend
RUN cd frontend && npm run build

FROM nginx:stable-alpine
COPY --from=builder /app/frontend/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
